services:
  sonarqube:
    image: sonarqube_flutter:9.9_0.5.1
    build:
      context: .
    networks:
      - scanner-sq-network
    container_name: sonarqube_flutter
    ports:
      - "9000:9000"
networks:
  scanner-sq-network:

